packages:
  - 'apps/*'
  - 'packages/*'
minimumReleaseAge: 10080
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lightningcss
  - msgpackr-extract
  - nx
  - unrs-resolver
ignoredBuiltDependencies:
  - msw
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  msw: false
  nx: true
  unrs-resolver: true
